{
  "id": "JavaScript The Definitive Guide (David Flanagan)_chunk_613",
  "content": "tes que o interpretador pule para \nseu novo destino.\nSe ocorre uma exceção no bloco \ntry e existe um bloco catch associado para tratar da exceção, o in-\nterpretador primeiramente executa o bloco \ncatch e depois o bloco finally. Se não há qualquer bloco \ncatch local para tratar da exceção, o interpretador primeiramente executa o bloco finally e depois \npula para a cláusula\n catch circundante mais próxima.\nSe o próprio bloco \nfinally causa um salto com uma instrução return, continue, break ou throw, ou \nchamando um método que lança uma exceção, o interpretador abandona o salto que estava",
  "metadata": {
    "source": "/home/jonata/Documentos/typescript-langchain/tmp/JavaScript The Definitive Guide (David Flanagan).pdf",
    "chunkIndex": 613,
    "totalChunks": 10000
  }
}